# Generated by Django 3.2.7 on 2021-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211103_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='git_url',
        ),
        migrations.AddField(
            model_name='project',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
