# Generated by Django 3.2.7 on 2021-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imageMain',
            field=models.ImageField(blank=True, upload_to='portfolio/images'),
        ),
    ]
